---
- name: copy motd
  become: yes
  copy:
    content: "{{ motd }}"
    dest: /etc/motd
  when: motd is defined

- name: install package for locales
  become: yes
  apt:
    name: locales
    state: present

- name: install locales
  become: yes
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items: "{{ locales }}"
